// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parason_Api.DTOs;

#nullable disable

namespace Parason_Api.Migrations
{
    [DbContext(typeof(CPQDbContext))]
    [Migration("20251022111506_initial-create")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parason_Api.Models.AttributeDef", b =>
                {
                    b.Property<int>("AttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeID"));

                    b.Property<string>("AttributeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttributeID");

                    b.ToTable("AttributeDefs");
                });

            modelBuilder.Entity("Parason_Api.Models.AttributeListValue", b =>
                {
                    b.Property<int>("ListValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListValueID"));

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Display")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ListValueID");

                    b.HasIndex("AttributeID");

                    b.ToTable("AttributeListValues");
                });

            modelBuilder.Entity("Parason_Api.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParentCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Parason_Api.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsConfigurable")
                        .HasColumnType("bit");

                    b.HasKey("EquipmentID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Parason_Api.Models.EquipmentAttribute", b =>
                {
                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<string>("AttributeCategory")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EquipmentID", "AttributeID");

                    b.HasIndex("AttributeID");

                    b.ToTable("L_Equipment_Attribute");
                });

            modelBuilder.Entity("Parason_Api.Models.GroupItem", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("GroupID", "ItemID");

                    b.HasIndex("ItemID");

                    b.ToTable("L_Group_Item");
                });

            modelBuilder.Entity("Parason_Api.Models.GroupMaster", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("GroupID");

                    b.ToTable("GroupMasters");
                });

            modelBuilder.Entity("Parason_Api.Models.ItemMaster", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DrawingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceMarkup")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("ItemMasters");
                });

            modelBuilder.Entity("Parason_Api.Models.Model", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModelDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<int>("SeriesID")
                        .HasColumnType("int");

                    b.HasKey("ModelID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SeriesID");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Parason_Api.Models.ModelAttributeValue", b =>
                {
                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("ListValueID")
                        .HasColumnType("int");

                    b.Property<int>("ModelID")
                        .HasColumnType("int");

                    b.Property<decimal?>("NumValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasIndex("AttributeID");

                    b.HasIndex("ListValueID");

                    b.HasIndex("ModelID");

                    b.ToTable("L_Model_AttributeValue");
                });

            modelBuilder.Entity("Parason_Api.Models.Price", b =>
                {
                    b.Property<decimal>("BasePriceINR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("ItemId");

                    b.HasIndex("ModelId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Parason_Api.Models.Process", b =>
                {
                    b.Property<int>("ProcessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProcessID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Parason_Api.Models.ProcessEquipment", b =>
                {
                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ProcessID", "EquipmentID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("L_Process_Equipment");
                });

            modelBuilder.Entity("Parason_Api.Models.ScopeOfSupply", b =>
                {
                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesID")
                        .HasColumnType("int");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("GroupID");

                    b.HasIndex("ItemId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SeriesID");

                    b.ToTable("Scope_Of_Supply");
                });

            modelBuilder.Entity("Parason_Api.Models.Series", b =>
                {
                    b.Property<int>("SeriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("SeriesDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SeriesID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EquipmentID");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.SeriesAttribute", b =>
                {
                    b.Property<int>("SeriesID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<string>("AttributeCategory")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeriesID", "AttributeID");

                    b.HasIndex("AttributeID");

                    b.ToTable("L_Series_Attribute");
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalArea", b =>
                {
                    b.Property<int>("VerticalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerticalID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("VerticalDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VerticalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("VerticalID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vertical_Area");
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalProcess", b =>
                {
                    b.Property<int>("VerticalID")
                        .HasColumnType("int");

                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("VerticalID", "ProcessID");

                    b.HasIndex("ProcessID");

                    b.ToTable("L_Vertical_Process");
                });

            modelBuilder.Entity("Parason_Api.Models.AttributeListValue", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("ListValues")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");
                });

            modelBuilder.Entity("Parason_Api.Models.Category", b =>
                {
                    b.HasOne("Parason_Api.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Parason_Api.Models.EquipmentAttribute", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("EquipmentAttributes")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("EquipmentAttributes")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Parason_Api.Models.GroupItem", b =>
                {
                    b.HasOne("Parason_Api.Models.GroupMaster", "Group")
                        .WithMany("GroupItems")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.ItemMaster", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Parason_Api.Models.ItemMaster", b =>
                {
                    b.HasOne("Parason_Api.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parason_Api.Models.Model", b =>
                {
                    b.HasOne("Parason_Api.Models.Series", "Series")
                        .WithMany("Models")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.ModelAttributeValue", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany()
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.AttributeListValue", "ListValue")
                        .WithMany()
                        .HasForeignKey("ListValueID");

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");

                    b.Navigation("ListValue");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Parason_Api.Models.Price", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID");

                    b.HasOne("Parason_Api.Models.ItemMaster", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.Navigation("Equipment");

                    b.Navigation("Item");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Parason_Api.Models.ProcessEquipment", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("ProcessEquipments")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Process", "Process")
                        .WithMany("ProcessEquipments")
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Parason_Api.Models.ScopeOfSupply", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID");

                    b.HasOne("Parason_Api.Models.GroupMaster", "Group")
                        .WithMany()
                        .HasForeignKey("GroupID");

                    b.HasOne("Parason_Api.Models.ItemMaster", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.HasOne("Parason_Api.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesID");

                    b.Navigation("Equipment");

                    b.Navigation("Group");

                    b.Navigation("Item");

                    b.Navigation("Model");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.Series", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("Series")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Parason_Api.Models.SeriesAttribute", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("SeriesAttributes")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Series", "Series")
                        .WithMany("SeriesAttributes")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalProcess", b =>
                {
                    b.HasOne("Parason_Api.Models.Process", "Process")
                        .WithMany("VerticalProcesses")
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.VerticalArea", "VerticalArea")
                        .WithMany("VerticalProcesses")
                        .HasForeignKey("VerticalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("VerticalArea");
                });

            modelBuilder.Entity("Parason_Api.Models.AttributeDef", b =>
                {
                    b.Navigation("EquipmentAttributes");

                    b.Navigation("ListValues");

                    b.Navigation("SeriesAttributes");
                });

            modelBuilder.Entity("Parason_Api.Models.Category", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Parason_Api.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentAttributes");

                    b.Navigation("ProcessEquipments");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.GroupMaster", b =>
                {
                    b.Navigation("GroupItems");
                });

            modelBuilder.Entity("Parason_Api.Models.Process", b =>
                {
                    b.Navigation("ProcessEquipments");

                    b.Navigation("VerticalProcesses");
                });

            modelBuilder.Entity("Parason_Api.Models.Series", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("SeriesAttributes");
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalArea", b =>
                {
                    b.Navigation("VerticalProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
