// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parason_Api.DTOs;

#nullable disable

namespace Parason_Api.Migrations
{
    [DbContext(typeof(CPQDbContext))]
    [Migration("20251024122817_SeedQuoteHeader")]
    partial class SeedQuoteHeader
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parason_Api.Models.AttributeDef", b =>
                {
                    b.Property<int>("AttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeID"));

                    b.Property<string>("AttributeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnitDefault")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttributeID");

                    b.HasIndex("AttributeCode")
                        .IsUnique();

                    b.ToTable("AttributeDef", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.AttributeListValue", b =>
                {
                    b.Property<int>("ListValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListValueID"));

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Display")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ListValueID");

                    b.HasIndex("AttributeID", "AttributeValue")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttrList");

                    b.ToTable("AttributeListValue", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipmentID");

                    b.HasIndex("EquipmentCode")
                        .IsUnique();

                    b.ToTable("Equipment", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.EquipmentAttribute", b =>
                {
                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<string>("AttributeCategory")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EquipmentID", "AttributeID");

                    b.HasIndex("AttributeID");

                    b.ToTable("L_Equipment_Attribute", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.EquipmentAttributeValue", b =>
                {
                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("ListValueID")
                        .HasColumnType("int");

                    b.Property<decimal?>("NumValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("EquipmentID", "AttributeID", "SequenceNo");

                    b.HasIndex("AttributeID");

                    b.HasIndex("ListValueID");

                    b.ToTable("L_Equipment_AttributeValue", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.ImageRef", b =>
                {
                    b.Property<int>("ImageRefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageRefID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagePurpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesID")
                        .HasColumnType("int");

                    b.HasKey("ImageRefID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("ModelID");

                    b.HasIndex("SeriesID");

                    b.ToTable("ImageRef", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.ItemMaster", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("ItemMaster", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.Model", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeriesID")
                        .HasColumnType("int");

                    b.HasKey("ModelID");

                    b.HasIndex("SeriesID", "ModelCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Model");

                    b.ToTable("Model", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.Price", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceID"));

                    b.Property<decimal>("BasePriceINR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EffectiveFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.HasKey("PriceID");

                    b.HasIndex("EquipmentID", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_Price_Equip")
                        .HasFilter("EquipmentID IS NOT NULL AND ModelID IS NULL AND ItemId IS NULL");

                    b.HasIndex("ItemId", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_Price_Item")
                        .HasFilter("ItemId IS NOT NULL AND EquipmentID IS NULL AND ModelID IS NULL");

                    b.HasIndex("ModelID", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_Price_Model")
                        .HasFilter("ModelID IS NOT NULL AND EquipmentID IS NULL AND ItemId IS NULL");

                    b.ToTable("Price", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.Process", b =>
                {
                    b.Property<int>("ProcessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProcessID");

                    b.HasIndex("ProcessCode")
                        .IsUnique();

                    b.ToTable("Process", "dbo");

                    b.HasData(
                        new
                        {
                            ProcessID = 1,
                            CreatedAt = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Yogesh P",
                            Description = "Stock Preparation",
                            IsActive = true,
                            ProcessCode = "LCP",
                            ProcessName = "Low Consistency Pulping"
                        },
                        new
                        {
                            ProcessID = 2,
                            CreatedAt = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Yogesh P",
                            Description = "Pulp Preparation",
                            IsActive = true,
                            ProcessCode = "HCP",
                            ProcessName = "High Consistency Pulping"
                        });
                });

            modelBuilder.Entity("Parason_Api.Models.ProcessEquipment", b =>
                {
                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ProcessID", "EquipmentID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("L_Process_Equipment", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.QuoteEquipmentOrModel", b =>
                {
                    b.Property<int>("QEOMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QEOMId"));

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price_INR")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesID")
                        .HasColumnType("int");

                    b.HasKey("QEOMId");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("ModelID");

                    b.HasIndex("SeriesID");

                    b.HasIndex("RecordID", "EquipmentID")
                        .IsUnique()
                        .HasDatabaseName("UX_QEOM_EQUIP")
                        .HasFilter("EquipmentID IS NOT NULL AND SeriesID IS NULL AND ModelID IS NULL");

                    b.HasIndex("RecordID", "ModelID")
                        .IsUnique()
                        .HasDatabaseName("UX_QEOM_MODEL")
                        .HasFilter("ModelID IS NOT NULL AND EquipmentID IS NULL AND SeriesID IS NULL");

                    b.HasIndex("RecordID", "SeriesID")
                        .IsUnique()
                        .HasDatabaseName("UX_QEOM_SERIES")
                        .HasFilter("SeriesID IS NOT NULL AND EquipmentID IS NULL AND ModelID IS NULL");

                    b.ToTable("Quote_Equipment_Or_Model", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.QuoteHeader", b =>
                {
                    b.Property<int>("QuoteID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<byte>("QuoteRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("INR");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("QuoteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<int>("ValidityDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.HasKey("QuoteID", "QuoteRevision");

                    b.ToTable("QuoteHeader", "dbo");

                    b.HasData(
                        new
                        {
                            QuoteID = 1,
                            QuoteRevision = (byte)1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "INR",
                            CustomerName = "ABC Industries",
                            Notes = "Seed sample quote",
                            QuoteName = "First Demo Quote",
                            QuoteNumber = "Q-2025-001",
                            Status = "Draft",
                            ValidityDays = 30
                        },
                        new
                        {
                            QuoteID = 2,
                            QuoteRevision = (byte)1,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Currency = "USD",
                            CustomerName = "XYZ Manufacturing",
                            Notes = "Second seed record",
                            QuoteName = "Second Demo Quote",
                            QuoteNumber = "Q-2025-002",
                            Status = "Approved",
                            ValidityDays = 45
                        });
                });

            modelBuilder.Entity("Parason_Api.Models.QuoteVertical", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<int>("QuoteID")
                        .HasColumnType("int");

                    b.Property<byte>("QuoteRevision")
                        .HasColumnType("tinyint");

                    b.Property<int>("VerticalID")
                        .HasColumnType("int");

                    b.HasKey("RecordID");

                    b.HasIndex("ProcessID");

                    b.HasIndex("VerticalID");

                    b.HasIndex("QuoteID", "QuoteRevision");

                    b.ToTable("Quote_Vertical", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.ScopeOfSupply", b =>
                {
                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price_INR")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("RecordID", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ModelID");

                    b.ToTable("ScopeOfSupply", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.Series", b =>
                {
                    b.Property<int>("SeriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SeriesID");

                    b.HasIndex("EquipmentID", "SeriesCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Series");

                    b.ToTable("Series", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.SeriesAttribute", b =>
                {
                    b.Property<int>("SeriesID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<string>("AttributeCategory")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeriesID", "AttributeID");

                    b.HasIndex("AttributeID");

                    b.ToTable("L_Series_Attribute", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.SpecDetails", b =>
                {
                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("ListValueID")
                        .HasColumnType("int");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<decimal?>("NumValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("RecordID", "AttributeID");

                    b.HasIndex("AttributeID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("ListValueID");

                    b.HasIndex("ModelID");

                    b.ToTable("Spec_Details", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalArea", b =>
                {
                    b.Property<int>("VerticalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerticalID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerticalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VerticalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("VerticalID");

                    b.HasIndex("VerticalCode")
                        .IsUnique();

                    b.ToTable("Vertical_Area", "dbo");

                    b.HasData(
                        new
                        {
                            VerticalID = 1,
                            CreatedAt = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Yogesh P",
                            Description = "Stock Preparation",
                            IsActive = true,
                            VerticalCode = "SPT",
                            VerticalName = "Stock Preparation"
                        },
                        new
                        {
                            VerticalID = 2,
                            CreatedAt = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Yogesh P",
                            Description = "Pulp Preparation",
                            IsActive = true,
                            VerticalCode = "PP",
                            VerticalName = "Pulp Preparation"
                        });
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalProcess", b =>
                {
                    b.Property<int>("VerticalID")
                        .HasColumnType("int");

                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("VerticalID", "ProcessID");

                    b.HasIndex("ProcessID");

                    b.ToTable("L_Vertical_Process", "dbo");
                });

            modelBuilder.Entity("Parason_Api.Models.AttributeListValue", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("ListValues")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");
                });

            modelBuilder.Entity("Parason_Api.Models.EquipmentAttribute", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("EquipmentAttributes")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("EquipmentAttributes")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Parason_Api.Models.EquipmentAttributeValue", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("EquipmentAttributeValues")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("EquipmentAttributeValues")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.AttributeListValue", "ListValue")
                        .WithMany("EquipmentAttributeValues")
                        .HasForeignKey("ListValueID");

                    b.Navigation("AttributeDef");

                    b.Navigation("Equipment");

                    b.Navigation("ListValue");
                });

            modelBuilder.Entity("Parason_Api.Models.ImageRef", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("ImageRefs")
                        .HasForeignKey("EquipmentID");

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany("ImageRefs")
                        .HasForeignKey("ModelID");

                    b.HasOne("Parason_Api.Models.Series", "Series")
                        .WithMany("ImageRefs")
                        .HasForeignKey("SeriesID");

                    b.Navigation("Equipment");

                    b.Navigation("Model");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.Model", b =>
                {
                    b.HasOne("Parason_Api.Models.Series", "Series")
                        .WithMany("Models")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.Price", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("Prices")
                        .HasForeignKey("EquipmentID");

                    b.HasOne("Parason_Api.Models.ItemMaster", "Item")
                        .WithMany("Prices")
                        .HasForeignKey("ItemId");

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany("Prices")
                        .HasForeignKey("ModelID");

                    b.Navigation("Equipment");

                    b.Navigation("Item");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Parason_Api.Models.ProcessEquipment", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("ProcessEquipments")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Process", "Process")
                        .WithMany("ProcessEquipments")
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Parason_Api.Models.QuoteEquipmentOrModel", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("QuoteEquipmentOrModels")
                        .HasForeignKey("EquipmentID");

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany("QuoteEquipmentOrModels")
                        .HasForeignKey("ModelID");

                    b.HasOne("Parason_Api.Models.QuoteVertical", "QuoteVertical")
                        .WithMany("QuoteEquipmentOrModels")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Series", "Series")
                        .WithMany("QuoteEquipmentOrModels")
                        .HasForeignKey("SeriesID");

                    b.Navigation("Equipment");

                    b.Navigation("Model");

                    b.Navigation("QuoteVertical");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.QuoteVertical", b =>
                {
                    b.HasOne("Parason_Api.Models.Process", "Process")
                        .WithMany("QuoteVerticals")
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.VerticalArea", "VerticalArea")
                        .WithMany("QuoteVerticals")
                        .HasForeignKey("VerticalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.QuoteHeader", "QuoteHeader")
                        .WithMany("QuoteVerticals")
                        .HasForeignKey("QuoteID", "QuoteRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("QuoteHeader");

                    b.Navigation("VerticalArea");
                });

            modelBuilder.Entity("Parason_Api.Models.ScopeOfSupply", b =>
                {
                    b.HasOne("Parason_Api.Models.ItemMaster", "Item")
                        .WithMany("ScopeOfSupplies")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany("ScopeOfSupplies")
                        .HasForeignKey("ModelID");

                    b.HasOne("Parason_Api.Models.QuoteVertical", "QuoteVertical")
                        .WithMany("ScopeOfSupplies")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Model");

                    b.Navigation("QuoteVertical");
                });

            modelBuilder.Entity("Parason_Api.Models.Series", b =>
                {
                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("Series")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Parason_Api.Models.SeriesAttribute", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("SeriesAttributes")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Series", "Series")
                        .WithMany("SeriesAttributes")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Parason_Api.Models.SpecDetails", b =>
                {
                    b.HasOne("Parason_Api.Models.AttributeDef", "AttributeDef")
                        .WithMany("SpecDetails")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.Equipment", "Equipment")
                        .WithMany("SpecDetails")
                        .HasForeignKey("EquipmentID");

                    b.HasOne("Parason_Api.Models.AttributeListValue", "ListValue")
                        .WithMany("SpecDetails")
                        .HasForeignKey("ListValueID");

                    b.HasOne("Parason_Api.Models.Model", "Model")
                        .WithMany("SpecDetails")
                        .HasForeignKey("ModelID");

                    b.HasOne("Parason_Api.Models.QuoteVertical", "QuoteVertical")
                        .WithMany("SpecDetails")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDef");

                    b.Navigation("Equipment");

                    b.Navigation("ListValue");

                    b.Navigation("Model");

                    b.Navigation("QuoteVertical");
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalProcess", b =>
                {
                    b.HasOne("Parason_Api.Models.Process", "Process")
                        .WithMany("VerticalProcesses")
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parason_Api.Models.VerticalArea", "VerticalArea")
                        .WithMany("VerticalProcesses")
                        .HasForeignKey("VerticalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Process");

                    b.Navigation("VerticalArea");
                });

            modelBuilder.Entity("Parason_Api.Models.AttributeDef", b =>
                {
                    b.Navigation("EquipmentAttributeValues");

                    b.Navigation("EquipmentAttributes");

                    b.Navigation("ListValues");

                    b.Navigation("SeriesAttributes");

                    b.Navigation("SpecDetails");
                });

            modelBuilder.Entity("Parason_Api.Models.AttributeListValue", b =>
                {
                    b.Navigation("EquipmentAttributeValues");

                    b.Navigation("SpecDetails");
                });

            modelBuilder.Entity("Parason_Api.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentAttributeValues");

                    b.Navigation("EquipmentAttributes");

                    b.Navigation("ImageRefs");

                    b.Navigation("Prices");

                    b.Navigation("ProcessEquipments");

                    b.Navigation("QuoteEquipmentOrModels");

                    b.Navigation("Series");

                    b.Navigation("SpecDetails");
                });

            modelBuilder.Entity("Parason_Api.Models.ItemMaster", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("ScopeOfSupplies");
                });

            modelBuilder.Entity("Parason_Api.Models.Model", b =>
                {
                    b.Navigation("ImageRefs");

                    b.Navigation("Prices");

                    b.Navigation("QuoteEquipmentOrModels");

                    b.Navigation("ScopeOfSupplies");

                    b.Navigation("SpecDetails");
                });

            modelBuilder.Entity("Parason_Api.Models.Process", b =>
                {
                    b.Navigation("ProcessEquipments");

                    b.Navigation("QuoteVerticals");

                    b.Navigation("VerticalProcesses");
                });

            modelBuilder.Entity("Parason_Api.Models.QuoteHeader", b =>
                {
                    b.Navigation("QuoteVerticals");
                });

            modelBuilder.Entity("Parason_Api.Models.QuoteVertical", b =>
                {
                    b.Navigation("QuoteEquipmentOrModels");

                    b.Navigation("ScopeOfSupplies");

                    b.Navigation("SpecDetails");
                });

            modelBuilder.Entity("Parason_Api.Models.Series", b =>
                {
                    b.Navigation("ImageRefs");

                    b.Navigation("Models");

                    b.Navigation("QuoteEquipmentOrModels");

                    b.Navigation("SeriesAttributes");
                });

            modelBuilder.Entity("Parason_Api.Models.VerticalArea", b =>
                {
                    b.Navigation("QuoteVerticals");

                    b.Navigation("VerticalProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
