// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Parason_Api.DTOs;

#nullable disable

namespace Parason_Api.Migrations
{
    [DbContext(typeof(CPQDbContext))]
    partial class CPQDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // VerticalArea entity
            modelBuilder.Entity("Parason_Api.Models.VerticalArea", b =>
                {
                    b.Property<int>("VerticalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerticalID"));

                    b.Property<string>("VerticalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VerticalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("VerticalID");

                    b.HasIndex("VerticalCode")
                        .IsUnique();

                    b.ToTable("VerticalArea", "dbo");

                    b.HasData(
                        new
                        {
                            VerticalID = 1,
                            VerticalCode = "SPT",
                            VerticalName = "Stock Preparation",
                            Description = "Stock Preparation",
                            IsActive = true,
                            CreatedAt = new DateTime(2025, 10, 23),
                            CreatedBy = "Yogesh P"
                        },
                        new
                        {
                            VerticalID = 2,
                            VerticalCode = "PP",
                            VerticalName = "Pulp Preparation",
                            Description = "Pulp Preparation",
                            IsActive = true,
                            CreatedAt = new DateTime(2025, 10, 23),
                            CreatedBy = "Yogesh P"
                        });
                });

            // Process entity
            modelBuilder.Entity("Parason_Api.Models.Process", b =>
                {
                    b.Property<int>("ProcessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessID"));

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ProcessID");

                    b.HasIndex("ProcessCode")
                        .IsUnique();

                    b.ToTable("Process", "dbo");

                    b.HasData(
                        new
                        {
                            ProcessID = 1,
                            ProcessCode = "LCP",
                            ProcessName = "Low Consistency Pulping",
                            Description = "Stock Preparation",
                            IsActive = true,
                            CreatedAt = new DateTime(2025, 10, 23),
                            CreatedBy = "Yogesh P"
                        },
                        new
                        {
                            ProcessID = 2,
                            ProcessCode = "HCP",
                            ProcessName = "High Consistency Pulping",
                            Description = "Pulp Preparation",
                            IsActive = true,
                            CreatedAt = new DateTime(2025, 10, 23),
                            CreatedBy = "Yogesh P"
                        });
                });

            // QuoteHeader entity
            modelBuilder.Entity("Parason_Api.Models.QuoteHeader", b =>
                {
                    b.Property<int>("QuoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteID"));

                    b.Property<byte>("QuoteRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("QuoteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("INR");

                    b.Property<int>("ValidityDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuoteID", "QuoteRevision");

                    b.ToTable("QuoteHeader", "dbo");

                    b.HasData(
                        new
                        {
                            QuoteID = 1,
                            QuoteRevision = (byte)1,
                            QuoteNumber = "Q-2025-001",
                            QuoteName = "First Demo Quote",
                            CustomerName = "ABC Industries",
                            Status = "Draft",
                            Currency = "INR",
                            ValidityDays = 30,
                            Notes = "Seed sample quote",
                            CreatedAt = new DateTime(2025, 1, 1),
                            CreatedBy = "System",
                            ModifiedAt = new DateTime(2025, 1, 1),
                            ModifiedBy = "Yogesh Patil"
                        },
                        new
                        {
                            QuoteID = 2,
                            QuoteRevision = (byte)1,
                            QuoteNumber = "Q-2025-002",
                            QuoteName = "Second Demo Quote",
                            CustomerName = "XYZ Manufacturing",
                            Status = "Approved",
                            Currency = "USD",
                            ValidityDays = 45,
                            Notes = "Second seed record",
                            CreatedAt = new DateTime(2025, 1, 2),
                            CreatedBy = "System",
                            ModifiedAt = new DateTime(2025, 1, 1),
                            ModifiedBy = "Yogesh Patil"
                        });
                });

#pragma warning restore 612, 618
        }
    }
}
